module.exports = {
  printWidth: 132,
  singleQuote: true,
  trailingComma: 'all',
  importOrder: [
    '<TYPES>^react',
    '<TYPES>',
    '<BUILTIN_MODULES>',
    '^react$',
    '^react-dom',
    '^react-router',
    '<THIRD_PARTY_MODULES>',
    '^~',
    '^[.]',
    '^react-icons',
    '.css$',
  ],
  importOrderTypeScriptVersion: '5.0.0',
  tailwindFunctions: ['cn', 'clsx', 'tv', 'classNames'],
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
};
